name: Publish Release
on:
  # run after the 'Generate Release' workflow completes
  workflow_run:
    workflows: ["Generate Release"]
    types: [completed]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    # only publish when the 'Generate Release' workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies ğŸ“¦
        run: npm ci

      - name: Build packages ğŸ› ï¸
        run: npm run build

      - name: Publish Oruga pre-release ğŸ›
        if: "github.event.prerelease" # only for pre-release
        working-directory: ./packages/oruga
        run: npm publish --tag pre

      - name: Publish Oruga release ğŸ›
        if: "!github.event.prerelease" # only for main release
        working-directory: ./packages/oruga
        run: npm publish

      - name: Publish Examples pre-release ğŸ¦‹
        if: "github.event.prerelease" # only for pre-release
        working-directory: ./packages/examples
        run: npm run publish:examples:pre

      - name: Publish Examples release ğŸ¦‹
        if: "!github.event.prerelease" # only for main release
        working-directory: ./packages/examples
        run: npm run publish:examples
